name: Auto Sync
on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync forked repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.4.0

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build

      - name: Add remote URL
        run: |
          git remote add forked_repo https://wuzoo:${{ secrets.GITHUB_TOKEN }}@github.com/wuzoo/WEB2_FE
          git config user.name wuzoo
          git config user.email wndyd9911@gmail.com

      - name: Push Changes to forked_repo
        run: |
          git push -f forked_repo main

      - name: Clean up
        run: |
          git remote remove forked_repo
